# Generated by Django 3.2.9 on 2021-12-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSuport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Proposed solutions', 'Proposed solutions'), ('Declined', 'Declined'), ('Resolved', 'Resolved')], default='Submitted', max_length=60)),
                ('issue', models.CharField(choices=[('Shipping', 'Shipping'), ('Product', 'Product'), ('Account', 'Account')], default=5, max_length=60)),
                ('message', models.TextField(max_length=500)),
                ('product', models.CharField(blank=True, max_length=60)),
                ('order_id', models.PositiveSmallIntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
