# Generated by Django 3.2.9 on 2021-12-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_user_profile'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersuport',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='customersuport',
            name='product',
        ),
        migrations.AddField(
            model_name='customersuport',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_support', to='checkout.order'),
        ),
        migrations.AddField(
            model_name='customersuport',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderline_support', to='checkout.orderline'),
        ),
        migrations.AlterField(
            model_name='customersuport',
            name='issue',
            field=models.CharField(choices=[('Order', 'Order'), ('Product', 'Product'), ('Account', 'Account')], default=5, max_length=60),
        ),
    ]
