# Generated by Django 3.2.9 on 2021-12-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replay',
        ),
    ]
