# Generated by Django 3.2.9 on 2021-12-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address_2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_town',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_postcode',
            new_name='postcode',
        ),
    ]
