# Generated by Django 3.2.9 on 2022-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211228_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unpaid',
            field=models.BooleanField(default=True),
        ),
    ]
