# Generated by Django 3.2.9 on 2021-12-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
