# Generated by Django 3.2.9 on 2022-01-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20220101_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Payment received', 'Payment received'), ('Proccessed', 'Proccessed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Submitted', max_length=50),
        ),
    ]
