# Generated by Django 3.2.9 on 2021-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PP', 'Pending Payment'), ('PSH', 'Pending Shipment'), ('SH', 'Shipped'), ('CA', 'Candelled'), ('CO', 'Completed')], default='PP', max_length=100),
        ),
    ]
