# Generated by Django 3.2.9 on 2021-12-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Pending Shipment', 'Pending Shipment'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending Payment', max_length=100),
        ),
    ]
