# Generated by Django 3.2.9 on 2021-12-15 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=5)),
                ('review', models.TextField(default='', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='shop.product')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
