# Generated by Django 3.2.9 on 2021-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211216_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_id',
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
