# Generated by Django 3.2.9 on 2021-12-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rarting',
            new_name='rating',
        ),
    ]
