# Generated by Django 3.2.9 on 2021-12-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_rarting_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
