# Generated by Django 3.2.9 on 2021-12-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='full_name',
        ),
    ]
