# Generated by Django 3.2.9 on 2021-12-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='phone',
        ),
    ]
